/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payroll;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.ImageIcon;

public class Budget extends javax.swing.JFrame {
Connection conn;
PreparedStatement pst;
ResultSet rs;
    /**
     * Creates new form Budget
     */
    public Budget() {
        initComponents();
          Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
       
        this.setTitle("  EMPLOYEE PAYROLL MANAGEMENT SYSTEM - CALCULATE BUDGET");
        ImageIcon img = new ImageIcon("images/logomini.png");
        this.setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        txt_salary = new javax.swing.JTextField();
        txt_allowance = new javax.swing.JTextField();
        txt_deduction = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txt_total = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_salary.setEditable(false);
        txt_salary.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_salary.setForeground(new java.awt.Color(238, 69, 64));
        txt_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_salaryActionPerformed(evt);
            }
        });
        getContentPane().add(txt_salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 140, 30));

        txt_allowance.setEditable(false);
        txt_allowance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_allowance.setForeground(new java.awt.Color(238, 69, 64));
        getContentPane().add(txt_allowance, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 140, 30));

        txt_deduction.setEditable(false);
        txt_deduction.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_deduction.setForeground(new java.awt.Color(238, 69, 64));
        getContentPane().add(txt_deduction, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 140, 30));

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 69, 64));
        jLabel1.setText("Total Salary:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 140, -1));

        jLabel2.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(238, 69, 64));
        jLabel2.setText("Total Allowance:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 69, 64));
        jLabel3.setText("Total Deduction:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 170, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(238, 69, 64));
        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 177, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(238, 69, 64));
        jButton2.setText("Calculate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 177, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(238, 69, 64));
        jButton3.setText("Calculate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 177, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 610, 210));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(238, 69, 64));
        jButton4.setText("Calculate total");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, 40));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(238, 69, 64));
        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 190, 40));

        txt_total.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        txt_total.setForeground(new java.awt.Color(238, 69, 64));
        txt_total.setText("AMOUNT");
        jPanel1.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 140, -1));

        jLabel4.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(238, 69, 64));
        jLabel4.setText("Total Expenditure:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 210, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_salaryActionPerformed
        // TODO add your handling code here:
           try{
            
           conn = DriverManager.getConnection("jdbc:mysql://localhost/payroll manager?serverTimezone=UTC","root","");
           String sql = "select sum(Salary) from infoStaff";
           
           pst = conn.prepareStatement(sql);
          
           rs=pst.executeQuery();
           
           if(rs.next()){
           String add1 = rs.getString("select sum(Salary) from infoStaff");
           txt_salary.setText(add1);
           System.out.print(sql);
        
           }
        }catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
        }
        finally
        {
         try{
        rs.close();
        pst.close();
        }
        catch(Exception e)
        {
            
        JOptionPane.showMessageDialog(null,e);
        
        }
        
        }
    }//GEN-LAST:event_txt_salaryActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try{
            
           conn = DriverManager.getConnection("jdbc:mysql://localhost/payroll manager?serverTimezone=UTC","root","");
           String sql = "select sum(Salary) from infoStaff";
           
           pst = conn.prepareStatement(sql);
          
           rs=pst.executeQuery();
           
           if(rs.next()){
           String add1 = rs.getString(1);
           txt_salary.setText(add1);
           System.out.print(pst.executeQuery());
        
           }
        }catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
        }
        finally
        {
         try{
        rs.close();
        pst.close();
        }
        catch(Exception e)
        {
            
        JOptionPane.showMessageDialog(null,e);
        
        }
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try{
            
           conn = DriverManager.getConnection("jdbc:mysql://localhost/payroll manager?serverTimezone=UTC","root","");
           String sql = "select sum(total_allowance) from allowance";
           
           pst = conn.prepareStatement(sql);
          
           rs=pst.executeQuery();
           
           if(rs.next()){
           String add1 = rs.getString(1);
           txt_allowance.setText(add1);
           System.out.print(pst.executeQuery());
        
           }
        }catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
        }
        finally
        {
         try{
        rs.close();
        pst.close();
        }
        catch(Exception e)
        {
            
        JOptionPane.showMessageDialog(null,e);
        
        }
        
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try{
            
           conn = DriverManager.getConnection("jdbc:mysql://localhost/payroll manager?serverTimezone=UTC","root","");
           String sql = "select sum(deduction_amount) from deduction";
           
           pst = conn.prepareStatement(sql);
          
           rs=pst.executeQuery();
           
           if(rs.next()){
           String add1 = rs.getString(1);
           txt_deduction.setText(add1);
          
        
           }
        }catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
        }
        finally
        {
         try{
        rs.close();
        pst.close();
        }
        catch(Exception e)
        {
            
        JOptionPane.showMessageDialog(null,e);
        
        }
        
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         float t_salary = Float.parseFloat(txt_salary.getText());
          float t_allowance = Float.parseFloat(txt_allowance.getText());
           float t_deduction = Float.parseFloat(txt_deduction.getText());
          
           
          float calcBudget = t_salary+t_allowance-t_deduction;
          String xP = String.valueOf(calcBudget);
          txt_total.setText(xP);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        txt_deduction.setText("");
        txt_allowance.setText("");
        txt_salary.setText("");
        txt_total.setText("");
   
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Budget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Budget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Budget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Budget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Budget().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txt_allowance;
    private javax.swing.JTextField txt_deduction;
    private javax.swing.JTextField txt_salary;
    private javax.swing.JLabel txt_total;
    // End of variables declaration//GEN-END:variables
}
