/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payroll;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *

 */
public class Designation extends javax.swing.JFrame {
Connection conn;
PreparedStatement pst;
ResultSet rs;
    /**
     * Creates new form Designation
     */
    public Designation() {
        initComponents();
           Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
       
        this.setTitle("  EMPLOYEE PAYROLL MANAGEMENT SYSTEM - DESIGNATION MANAGER");
        ImageIcon img = new ImageIcon("images/logomini.png");
        this.setIconImage(img.getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_empid = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txt_designation = new javax.swing.JTextField();
        txt_salary = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(238, 69, 64));
        jLabel18.setText("DESIGNATION:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 120, 40));

        jLabel15.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(238, 69, 64));
        jLabel15.setText("EMPLOYEE ID :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 120, 40));

        txt_empid.setEditable(false);
        txt_empid.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        txt_empid.setForeground(new java.awt.Color(238, 69, 64));
        getContentPane().add(txt_empid, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 200, 30));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(238, 69, 64));
        jLabel16.setText("SEARCH EMPLOYEE : ");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 30));

        txt_search.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        txt_search.setForeground(new java.awt.Color(238, 69, 64));
        txt_search.setToolTipText("ENTER EMPLOYEE ID");
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        jPanel2.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 280, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 520, 70));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_designation.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        txt_designation.setForeground(new java.awt.Color(238, 69, 64));
        jPanel3.add(txt_designation, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 200, 30));

        txt_salary.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        txt_salary.setForeground(new java.awt.Color(238, 69, 64));
        jPanel3.add(txt_salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 200, 30));

        jLabel14.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(238, 69, 64));
        jLabel14.setText("SALARY:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 520, 200));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Eras Bold ITC", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(238, 69, 64));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll/delete.png"))); // NOI18N
        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 190, 50));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Eras Bold ITC", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(238, 69, 64));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll/clear.png"))); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 190, 50));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(238, 69, 64));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll/add.png"))); // NOI18N
        jButton1.setText("ADD RECORD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 190, 50));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Eras Bold ITC", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(238, 69, 64));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll/update.png"))); // NOI18N
        jButton5.setText("UPDATE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 190, 50));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 520, 170));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:

        try{
            conn = DriverManager.getConnection("jdbc:mysql://localhost/payroll manager?serverTimezone=UTC","root","");
            String sql ="select * from designation where id=? ";

            pst=conn.prepareStatement(sql);
            pst.setString(1,txt_search.getText());
            rs=pst.executeQuery();

            if(rs.next()){

                String add1 =rs.getString("id");
                txt_empid.setText(add1.toString());

                String add2 =rs.getString("position");
                txt_designation.setText(add2);

                String add3 =rs.getString("salary");
                txt_salary.setText(add3);

              
            }

        }catch(Exception e){

        }
        finally {

            try{

                rs.close();

                pst.close();

            }
            catch(Exception e){

            }
        }
    }//GEN-LAST:event_txt_searchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to add record?", "Add Record", JOptionPane.YES_NO_OPTION);
        if(x==0){
            try {
                conn = DriverManager.getConnection("jdbc:mysql://localhost/payroll manager?serverTimezone=UTC","root","");
                String sql ="insert into designation "
                + "(position,salary)"
                + " values (?,?) ";

                pst=conn.prepareStatement(sql);
                pst.setString(1,txt_designation.getText());
                pst.setString(2,txt_salary.getText());
              

                pst.execute();
                JOptionPane.showMessageDialog(null,"Data is saved successfully");

            }
            catch (Exception e)

            {
                JOptionPane.showMessageDialog(null,e);
            }

            try {
                conn = DriverManager.getConnection("jdbc:mysql://localhost/payroll manager?serverTimezone=UTC","root","");
                String sq = "select * from infostaff where (id) NOT IN (SELECT id from login)";

                pst = conn.prepareStatement(sq);
                rs = pst.executeQuery();

                while(rs.next()){

                    String add1 = rs.getString("id");
                    String add2 = rs.getString("first_name");
                    String add3 = rs.getString("Dob");
                    String result = add3.replace("/","");
                    String add4 = rs.getString("Department");

                    String sql = "insert into login ( username,password,division,emp_id) values ('"+add2+"','"+result+"','"+add4+"','"+add1+"')";
                    pst = conn.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null,"User Account has been created successfully: " +" Username: "+add2+" Password: " +result );
                }

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }

            finally {

                try{
                    rs.close();
                    pst.close();

                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,e);
                }

            }

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete record?", "Delete Record", JOptionPane.YES_NO_OPTION);
        if(x==0){          // TODO add your handling code here:

            try{
                conn = DriverManager.getConnection("jdbc:mysql://localhost/payroll manager?serverTimezone=UTC","root","");
                String sql ="delete from designation where id=? ";
                pst=conn.prepareStatement(sql);
                pst.setString(1, txt_empid.getText());
                pst.execute();

                JOptionPane.showMessageDialog(null,"Record Deleted");

            }catch(Exception e){

                JOptionPane.showMessageDialog(null, e);
            }finally {

                try{
                    rs.close();
                    pst.close();

                }
                catch(Exception e){

                }
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to update record?", "Update Record", JOptionPane.YES_NO_OPTION);
        if(x==0){          // TODO add your handling code here:

            try{
                
             String id = txt_empid.getText();
             String position = txt_designation.getText();
             String salary = txt_salary.getText();
             
             
          
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/payroll manager?serverTimezone=UTC","root","");
            pst = conn.prepareStatement("update designation set position = ?, salary=? where id =?");
            
            
            pst.setString(1, position);
            pst.setString(2, salary);
            pst.setString(3, id);
                JOptionPane.showMessageDialog(null, "Record Updated");

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }finally {

                try{
                    rs.close();
                    pst.close();

                }
                catch(Exception e){

                }
            }

        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        txt_empid.setText("");
        txt_search.setText("");
        txt_salary.setText("");
         txt_designation.setText("");
     
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Designation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Designation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Designation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Designation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Designation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txt_designation;
    private javax.swing.JTextField txt_empid;
    private javax.swing.JTextField txt_salary;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
