/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payroll;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.DriverManager;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class SalaryIncrement extends javax.swing.JFrame {
Connection conn;
PreparedStatement pst;
ResultSet rs;
/**
     * Creates new form SalaryIncrement
     */
    public SalaryIncrement() {
        initComponents();
          Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
       
        this.setTitle("  EMPLOYEE PAYROLL MANAGEMENT SYSTEM - CALCULATE INCREMENT");
        ImageIcon img = new ImageIcon("images/logomini.png");
        this.setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_salary = new javax.swing.JTextField();
        duration = new javax.swing.JComboBox<>();
        txt_search = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txt_empid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_update = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_salary.setEditable(false);
        txt_salary.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        txt_salary.setForeground(new java.awt.Color(238, 69, 64));
        getContentPane().add(txt_salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 170, 30));

        duration.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        duration.setForeground(new java.awt.Color(238, 69, 64));
        duration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6 Months", "1 Year", "1 Year 6 Months", "2 Years", "2 Year 6 Months", "3 Years", "3 Year 6 Months", "4 Years", "4 Year 6 Months", "5 Years", "5 Year 6 Months", "6 Years", "6 Year 6 Months", "7 Years", "7 Year 6 Months", "8 Years", "8 Year 6 Months", "9 Years", "9 Year 6 Months", "10 Years", " " }));
        getContentPane().add(duration, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 218, 170, 40));

        txt_search.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        txt_search.setForeground(new java.awt.Color(238, 69, 64));
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        getContentPane().add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 257, 40));

        jLabel3.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 69, 64));
        jLabel3.setText("Search ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 120, -1));

        jLabel4.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(238, 69, 64));
        jLabel4.setText("Base Salary");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 130, -1));

        jLabel5.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(238, 69, 64));
        jLabel5.setText("Duration Completed");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jButton2.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(238, 69, 64));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll/update.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 180, 60));

        txt_empid.setEditable(false);
        txt_empid.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        txt_empid.setForeground(new java.awt.Color(238, 69, 64));
        getContentPane().add(txt_empid, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 170, 30));

        jLabel2.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(238, 69, 64));
        jLabel2.setText("Employee Id");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 130, 22));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 610, 60));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 610, 180));

        jButton1.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(238, 69, 64));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll/calculate.png"))); // NOI18N
        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 170, 60));

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 69, 64));
        jLabel1.setText("Updated Salary:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 160, -1));

        txt_update.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        txt_update.setForeground(new java.awt.Color(238, 69, 64));
        txt_update.setText("Amount");
        jPanel1.add(txt_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
         try{
            conn = DriverManager.getConnection("jdbc:mysql://localhost/payroll manager?serverTimezone=UTC","root","");
            String sql ="select * from infostaff where id=? ";

            pst=conn.prepareStatement(sql);
            pst.setString(1,txt_search.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                String add1 = rs.getString("id");
           txt_empid.setText(add1);
           
                String add2 =rs.getString("Salary");
                txt_salary.setText(add2);

               

            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally {

            try{

                rs.close();
                pst.close();

            }
            catch(Exception e){

            }
        }
         

    }//GEN-LAST:event_txt_searchKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
         try{
          conn = DriverManager.getConnection("jdbc:mysql://localhost/payroll manager?serverTimezone=UTC","root","");
             String value1 = txt_empid.getText();
             String value2 = txt_update.getText();
             
             String sql ="update infostaff set id = '"+value1+"', salary = '"+value2+"' where id = '"+value1+"' ";
             pst = conn.prepareStatement(sql);
             pst.execute();
             JOptionPane.showMessageDialog(null, "Record Updated");
             
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        } finally
        {
         try{
        rs.close();
        pst.close();
        }
        catch(Exception e)
        {
            
        JOptionPane.showMessageDialog(null,e);
        
        }
        
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int salary = Integer.parseInt(txt_salary.getText());
          
        
         String value12 = duration.getSelectedItem().toString();
        if(value12 == "6 Months" ||value12 == "1 Year" ||value12 == "1 Year 6 Months" ||value12 == "2 Years" ||value12 == "2 Year 6 Months" ||value12 == "3 Years"
                ||value12 == "3 Year 6 Months" ||value12 == "4 Years"||value12 == "4 Year 6 Months" ){
         int calcPercentage = salary/100 * 2 +salary;
          String xP = String.valueOf(calcPercentage);
          txt_update.setText(xP);
        }
        else if(value12 == "5 Years" ||value12 == "5 Year 6 Months"
                ||value12 == "6 Years"||value12 == "6 Year 6 Months" || value12 == "7 Years" ||value12 == "7 Year 6 Months"
                ||value12 == "8 Years"||value12 == "8 Year 6 Months"||value12 == "9 Years"||value12 == "9 Year 6 Months"||value12 == "10 Years"){
         int calcPercentage = salary/100 * 5 +salary;
          String xP = String.valueOf(calcPercentage);
          txt_update.setText(xP);
        }
          
    }//GEN-LAST:event_jButton1ActionPerformed


            

       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalaryIncrement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalaryIncrement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalaryIncrement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalaryIncrement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalaryIncrement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> duration;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txt_empid;
    private javax.swing.JTextField txt_salary;
    private javax.swing.JTextField txt_search;
    private javax.swing.JLabel txt_update;
    // End of variables declaration//GEN-END:variables
}
